language: rust
rust:
  - nightly

cache:
  - apt
  - homebrew
  - cargo

matrix:
  include:
    - env: ARCH=i686-unknown-linux-gnu
      os: linux
    - env: ARCH=x86_64-unknown-linux-gnu
      os: linux
    - env: ARCH=i686-pc-windows-msvc
      os: windows
    - env: ARCH=x86_64-pc-windows-msvc
      os: windows
    - env: ARCH=x86_64-apple-darwin
      os: osx
    - env: ARCH=i686-apple-darwin
      os: osx
  #fermium doesn't fully work on 32bit targets at the moment
  allow_failures:
    - env: ARCH=i686-apple-darwin
      os: osx
    - env: ARCH=i686-unknown-linux-gnu
      os: linux
    - env: ARCH=i686-pc-windows-msvc
      os: windows

addons:
  apt:
    packages:
      - build-essential
      - libgtk-3-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
  homebrew:
    update: true
    packages:
      - sdl2
      - sdl2-image
      - sdl2-mixer
      - sdl2-ttf

script:
  - rustup default nightly
  - rustup target add $ARCH
  - rustup update
  - cargo build --target=$ARCH
  - cargo test --target=$ARCH
  #test no-std
  - cargo test --target=$ARCH --lib rusty-boy-advance --no-default-features
  - cargo bench --target=$ARCH
  - |
    if [ $ARCH == "x86_64-unknown-linux-gnu" ]; then
      export DO_DEPLOY="yes";
    fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: public
  on:
    branch: master
    condition: $DO_DEPLOY = yes

before_deploy:
  - cargo doc --document-private-items --no-deps
  - mkdir public
  - cp -r target/doc public/
  - pwd
  - ls
  - echo "<meta http-equiv=refresh content=0;url=doc/rusty_boy_advance/index.html>" > public/index.html
