language: rust
rust:
  - nightly
  
cache:
  - apt
  - homebrew
  - cargo
matrix:
  include:
  - env: ARCH=x86_64
    os: linux
    deploy:
    - provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      keep-history: false
      local-dir: public
      on:
        branch: master
  - env: ARCH=i686
    os: linux
  - env: ARCH=x86_64
    os: windows
  - env: ARCH=i686
    os: windows
  - env: ARCH=x86_64
    os: osx
  - env: ARCH=i686
    os: osx

addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev
    - libegl1-mesa-dev
    - libgles2-mesa-dev
  homebrew:
    update: true
    packages:
    - sdl2
    - sdl2-image
    - sdl2-mixer
    - sdl2-ttf

before_deploy:
  - cargo bench
  - cargo doc --document-private-items --no-deps
  - mkdir public
  - cp -r target/doc public/
  - if [ $TRAVIS_OS_NAME == "windows" ]; then
      cp -r target/doc C:/Users/travis/build/nico-abram/rusty-boy-advance/public.;
      fi;
  - pwd
  - ls
- echo "<meta h
