language: rust
rust:
  - nightly
  
cache:
  - apt
  - cargo

before_install:
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libegl1-mesa-dev libgles2-mesa-dev

before_deploy:
  - cargo doc --document-private-items --no-deps
  - mkdir public
  - cp -r target/doc public/
  - pwd
  - ls
  - echo "<meta http-equiv=refresh content=0;url=doc/rgba/index.html>" > public/index.html
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: public
  on:
    branch: master
