[package]
name = "rgba"
version = "0.0.0"
authors = ["Nicolas <abramlujan@gmail.com>"]
edition = "2018"

readme = "README.md"
keywords = ["emulator", "gba", "game boy"]
license = "MIT"

[dependencies]
clap = "2.33.0"
byteorder = "1.3.2"
beryllium = "0.0.11"